.gitignore
Growthook/Growthook.xcodeproj/project.pbxproj
Growthook/Growthook.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

- xcodeproj 파일이 안올라가서 gitignore 파일 수정해서 다시 올립니당
- Resolved: #4

[Fix] #4 - gitignore 파일 수정

---

Growthook/Growthook/Presentation/Insights/Controllers/CreatingNewInsightsViewController.swift

- 
- TextView 의 경우, UIControl.Event 에 따른 Border 의 색이 변하는데 TextField 가 변하지 않아서 그걸 수정했습니다. 빠른 어푸루부 부탁드릴게용~~! ㅎ

[Feat] #28 - TextField 에 Border 색을 입히는걸 깜빡했습니다. 수정했습니다.

---

Growthook/Growthook.xcodeproj/project.pbxproj
Growthook/Growthook/Global/Extension/Encodable+.swift
Growthook/Growthook/Info.plist
Growthook/Growthook/Network/Base/URLConstant.swift

- 서버 초기세팅
- base URL 추가
- 현재까지 구현된 API path 추가
- API 폴더 안에 있는 API 파일은 제가 나중에 지울게요 다른 분들은 그 안에 폴더 만드셔서 작업하시면 됩니다.
- Resolved: #42

[Setting] #42 - 서버 초기세팅

---

Growthook/Growthook.xcodeproj/project.pbxproj
Growthook/Growthook/Growthook.entitlements

- 애플 개발자 계정이 있어야 합니다.
- 앱 번들 Id 를 바꿨습니다.
- Sign in Apple Entitlement 를 추가했습니다.
- Resolved: #66

[Add] #66 - 애플 로그인에 필요한 초기 세팅을 완료했습니다.

---

Growthook/Growthook/Application/SceneDelegate.swift
Growthook/Growthook/Presentation/CreateAction/ViewController/CreateActionViewControlller.swift
Growthook/Growthook/Presentation/CreateAction/ViewModel/CreateActionViewModel.swift
Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
Growthook/Growthook/Presentation/InsightsDetail/Controllers/InsightsDetailViewController.swift

- 동굴생성뷰 post API의 memberId를 UserDefaults에서 가져왔습니다. 
- 액션플랜 생성에서 seedId를 액션플랜뷰에서 가져왔습니다. 
- 서버통신 수정 
- Resolved: #61

[Fix] #61 - SeedId 수정

---

Growthook/Growthook.xcodeproj/project.pbxproj
Growthook/Growthook/Data/MyPage/MyPageDTO.swift
Growthook/Growthook/Presentation/Mypage/ViewModels/MyPageViewModel.swift

- 마이페이지 프로필 API 에 프로필 이미지 url 추가됨
- API 코드 수정

[Feature] - #74 마이페이지의 수정된 API 를 반영했습니다.

---

Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift

[Fix] #84 - 홈, 동굴 상세 뷰 서버통신 반영

---

Growthook/Growthook.xcodeproj/project.pbxproj
Growthook/Growthook/Application/SplashViewController.swift
Growthook/Growthook/Application/TokenManager.swift
Growthook/Growthook/Global/Extension/Observable+.swift
Growthook/Growthook/Network/API/ActionList/ActionListService.swift
Growthook/Growthook/Network/API/Auth/AuthAPI.swift
Growthook/Growthook/Network/API/CreateAction/CreateActionService.swift
Growthook/Growthook/Network/API/CreateCave/CreateCaveService.swift
Growthook/Growthook/Network/API/Insights/InsightsDetailService.swift
Growthook/Growthook/Network/API/Insights/InsightsService.swift
Growthook/Growthook/Network/API/MyPage/MyPageService.swift
Growthook/Growthook/Network/APIService/Home/SeedListTarget.swift
Growthook/Growthook/Network/ServiceError/ServiceError.swift
Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift

- 토큰으로 인한 재시도 문제를 없애고자 rxMoya 를 사용하는 메서드에서는 문제없이 토큰을 재발급 받고 해당 API 를 재실행합니다.
https://github.com/Team-Growthook/Growthook-iOS/blob/736309f0161ca4d415b8d7e5bcbb4cd863594552/Growthook/Growthook/Global/Extension/Observable%2B.swift#L63-L80
- Resolved: #74

[Fix] - #74 토큰 만료로 인한 재시도 오퍼레이터 추가

---

Growthook/Growthook/Data/Insights/InsightsDTO.swift
Growthook/Growthook/Network/API/CreateAction/CreateActionService.swift
Growthook/Growthook/Presentation/Insights/ViewModels/InsightsViewModel.swift
Growthook/Growthook/Presentation/InsightsDetail/Controllers/InsightDetailEditSeedViewController.swift
Growthook/Growthook/Presentation/InsightsDetail/Controllers/InsightsDetailViewController.swift
Growthook/Growthook/Presentation/InsightsDetail/ViewModels/InsightsDetailViewModel.swift
Growthook/Growthook/Presentation/InsightsDetail/Views/InsightsDetailMemoView.swift
Growthook/Growthook/Presentation/Mypage/Controllers/MyPageUserInformationViewController.swift

- 디코딩 에러를 고쳐 UI 이슈를 해결했습니다.
- 마이페이지 네비바 이슈를 해결했습니다

[Fix] - #74 디코딩 에러 픽스

---

Growthook/Growthook/Data/ActionList/ActionListDTO.swift
Growthook/Growthook/Network/API/ActionList/ActionListService.swift
Growthook/Growthook/Network/Base/URLConstant.swift
Growthook/Growthook/Presentation/ActionList/Cell/ActionListCompleteTableViewCell.swift
Growthook/Growthook/Presentation/ActionList/Controllers/CompleteViewController.swift
Growthook/Growthook/Presentation/ActionList/Controllers/InprogressViewController.swift
Growthook/Growthook/Presentation/ActionList/ViewModels/ActionListViewModel.swift

- 스크랩 버튼 기능 누락 구현
- 진행중, 완료 탭에서 스크랩 버튼을 누르면 스크랩이 되도록 구현했습니다
- Resolved: #90

[Feature] #90 - 수정사항 반영 및 추가 구현

---

Growthook/Growthook/Presentation/CreateAction/View/InsightView.swift
Growthook/Growthook/Presentation/CreateAction/ViewController/CreateActionViewControlller.swift
Growthook/Growthook/Presentation/InsightsDetail/Controllers/InsightsDetailViewController.swift
Growthook/Growthook/Presentation/InsightsDetail/Views/InsightsDetailMainBlockView.swift
Growthook/Growthook/Presentation/Onboarding/ViewControllers/OnboardingSelectViewController.swift

- 안된거: InsightsDetailViewController -> CreateActionViewControlller 상태에서 pop해서 다시 InsightsDetailViewController로 돌아갈때 액션플랜이 반영이 안됩니다. 
- 여기에  init(hasAnyActionPlan: Bool, seedId: Int) 으로 true로 바꿔야하는데 pop을 해서 선언을 다시 하는게 아니라서 어떻게 바꿔야 할까요... @PecanPiePOS 
- 
- Resolved: #

[Fix] #82 - UI 수정사항 반영

---

Growthook/Growthook.xcodeproj/project.pbxproj
Growthook/Growthook/Global/Extension/UILabel+.swift
Growthook/Growthook/Global/Literals/StringLiterals.swift
Growthook/Growthook/Presentation/Mypage/Controllers/LogoutAlertViewController.swift
Growthook/Growthook/Presentation/Mypage/Controllers/MyPageUserInformationViewController.swift
Growthook/Growthook/Presentation/Mypage/Controllers/MypageViewController.swift
Growthook/Growthook/Presentation/Mypage/Views/MyPageAlertView.swift

[Fix] #98 - 마이페이지 탈퇴, 로그아웃 기능 추가

---

Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
Growthook/Growthook/Presentation/Mypage/Controllers/MyPageUserInformationViewController.swift

- 프로필 사진이 하나 더 있었습니다.. 
- 프로필 사진 변경
- Resolved: #102

[Fix] #102 - 프로필 이미지 변경

---

Growthook/Growthook/Presentation/CaveDetail/ViewControllers/RemoveCaveAlertViewController.swift

- 동굴 뷰에서 인사이트 삭제 이후 반영 안되는 에러 수정
- Resolved: #105

[Fix] #105 - 동굴 뷰에서 인사이트 삭제 이후 반영 안되는 에러 수정

---

Growthook/Growthook.xcodeproj/project.pbxproj

앱 이름을 한글로 표시합니다.

---

Growthook/Growthook/Presentation/Home/Views/HomeCaveView.swift

[Fix] #108 - 동굴 엠티 뷰 라벨 레이아웃 수정

---

Growthook/Growthook/Info.plist
Growthook/Growthook/Presentation/CreateAction/View/CreateActionView.swift

- 액션플랜 생성 뷰 확인 버튼 비활성화
- 
- Resolved: #103

[Fix] #102 - 액션플랜 생성 뷰 확인 버튼 비활성화

---

Growthook/Growthook/Network/API/Auth/AuthAPI.swift
Growthook/Growthook/Network/API/CaveAPI/CaveAPI.swift
Growthook/Growthook/Network/API/SeedListAPI/SeedListAPI.swift
Growthook/Growthook/Network/API/SsukAPI/SsukAPI.swift
Growthook/Growthook/Presentation/CaveDetail/ViewModels/ChangeCaveViewModel.swift
Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift

[Fix] #113 - API 수정

---

Growthook/Growthook/Application/TokenManager.swift
Growthook/Growthook/Info.plist

[Fix] - #74 Refresh Token 만료 이슈 해결

---

Growthook/Growthook/Application/SplashViewController.swift

[Fix] #115 - 스플래시 뷰 로직 수정
